/** What shipped, keyed to screens — so the wall reflects terminal work. Newest first. Claude appends on each ship. */
export const CHANGES: { date: string; screen: string; what: string; pr: number }[] = [
  { date: "2026-09-03", screen: "V2", what: "A correct-but-slow answer no longer repeats the answer in a second format; the reveal only appears on a miss, with any secondary form (2.2 billion) on a quieter line. Tutor sentences now written for every family — fractions, decimals, place value, scientific notation, magnitude, combinations — so the one-line working never shows", pr: 72 },
  { date: "2026-09-03", screen: "designspace", what: "Widgets page: the ten K-12 conceptual ideas ranked for Drill, each with the representations the literature uses, what an interactive version would do, and the skills it serves; the minimal set of four pictures (Array, Bar, Line, Chain) that carries the list; libraries worth mining. ★ / ✕ / notes per row, handles W-<id>", pr: 71 },
  { date: "2026-09-03", screen: "V1", what: "The version, built: the question as a top-left caption (serif, no reflow between states), the calculator keypad with e and /, the session as a line across the top (tap to change length), and a miss that speaks in the tutor's sentences — in this item's numbers — with the picture in the keypad's place. Sentences written for the arithmetic and percent families; the rest fall back to the one-line working for now", pr: 70 },
  { date: "2026-09-03", screen: "D-widgets", what: "Widgets is a decision: the three built pictures (area model, multiplier chain, log number line — playable full-size) and three proposed (fraction strip, place-value slider, sharing array), each shown inside the Miss screen with its own worked miss and the skills it serves; the skills with no picture listed. Controls simplified: ★ shortlists, ✕ rules out, a picker chooses among several stars; yes/maybe retired (your yes's became stars)", pr: 69 },
  { date: "2026-09-03", screen: "designspace", what: "Decisions reorganized: the version at the top (composed from the stars), then decisions by status — working on / later / decided — with priority order, a copyable brief and link per decision; the Miss screen is one decision with two axes; stars and reactions now actually save (the notes API had been rejecting ★ and ↕ keys)", pr: 68 },
  { date: "2026-09-03", screen: "D-miss", what: "Miss screen: feedback voice × widget placement composed, with the full pairing grid", pr: 67 },
  { date: "2026-09-02", screen: "designspace", what: "Galaxy Brain → Decisions: per decision, editable requirements, the live choice, and options to star/prune; the stars are the spec", pr: 66 },
  { date: "2026-09-02", screen: "designspace", what: "Reactions (yes / maybe / no) on directions and variants; no collapses the row; included in copy-all", pr: 65 },
  { date: "2026-09-02", screen: "designspace", what: "Galaxy Brain refocused: 5 complete directions (incl. Current as baseline) + a Dial-in variants sheet for Quiet; Tailwind now scans content/ (mocks were unstyled)", pr: 64 },
  { date: "2026-09-02", screen: "designspace", what: "Galaxy Brain as a contact sheet: 16 directions, by-step / by-direction lenses, size slider, lightbox", pr: 63 },
  { date: "2026-09-02", screen: "designspace", what: "Galaxy Brain as a board: directions × flow, stars, play-the-flow, composed flow from stars", pr: 62 },
  { date: "2026-09-02", screen: "designspace", what: "Laptop frames at full width (actual size on large monitors); rails re-flow", pr: 60 },
  { date: "2026-09-02", screen: "designspace", what: "Screens: Phone / Laptop toggle", pr: 59 },
  { date: "2026-09-02", screen: "designspace", what: "Copy feedback: this note · this screen · everything, as one paste-ready block", pr: 58 },
  { date: "2026-09-02", screen: "designspace", what: "Screens wall: sticky component rail, notes pinned to screens and components, click-to-copy handles, Changes feed", pr: 57 },
  { date: "2026-09-02", screen: "designspace", what: "Components as annotated real screens (auto-measured callouts)", pr: 55 },
  { date: "2026-09-02", screen: "designspace", what: "Catalog frames at a true 390×844 viewport", pr: 54 },
  { date: "2026-09-02", screen: "V2", what: "Feedback takes the whole screen: keypad hidden, → bar", pr: 52 },
  { date: "2026-09-02", screen: "V2", what: "Explicit → button to advance", pr: 51 },
  { date: "2026-09-02", screen: "V2", what: "Widgets seeded with the missed item's numbers", pr: 50 },
  { date: "2026-09-02", screen: "V1", what: "Timer freezes from submit until the next item", pr: 47 },
  { date: "2026-09-02", screen: "V2", what: "Tips only show for numbers they fit; no placeholder in the answer box", pr: 44 },
];
